# Whenever a tag push matching pattern "v*" then run the job
on: 
  push:
    tags:
      - "v*"

env:
  itchio_account: madhax1
  itchio_project: dodge-the-creeps
  itchio_channel: HTML
  BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}


jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v4
    - name: export game
      id: export
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
    - name: create release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
    - name: Upload to itch.io
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler push ${{ steps.export.outputs.build_directory }} ${{ env.itchio_account }}/${{ env.itchio_project }}:${{ env.itchio_channel }}
